spring:
  application:
    name: deepseek-demo

  ai:
    deepseek:
      api-key: ${DP-API-KEY}
      chat:
        options:
          model: deepseek-v3
#          model: deepseek-r1
      base-url: ${DP-API-URL}

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: #debug
                SimpleLoggerAdvisor: DEBUG  # 单独该日志打印
