spring:
  application:
    name: deepseek-demo

  ai:
    deepseek:
      api-key: ${DP-API-KEY}
      chat:
        options:
          model: deepseek-v3
#          model: deepseek-r1
      base-url: ${DP-API-URL}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/sql/schema-mysql.sql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_ai_demo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: #debug
                SimpleLoggerAdvisor: DEBUG  # 单独该日志打印
